FROM python:3.7

MAINTAINER mohamedgaberelbahr@gmail.com

RUN pip install --upgrade pip

RUN mkdir /app

WORKDIR /app

COPY requirements.txt .

RUN pip install -r /app/requirements.txt

COPY . /app

EXPOSE 8080

CMD ["gunicorn", "--workers", "16", "-b", "0.0.0.0:8080", "app:app", "--reload"]
